const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST';
const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL';
const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS';
const EMPLOYEE_DETAILS_REQUEST = 'EMPLOYEE_DETAILS_REQUEST';
const EMPLOYEE_DETAILS_SUCCESS = 'EMPLOYEE_DETAILS_SUCCESS';
const EMPLOYEE_DETAILS_FAIL = 'EMPLOYEE_DETAILS_FAIL';
const EMPLOYEE_ADD_REQUEST = 'EMPLOYEE_ADD_REQUEST';
const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS';
const EMPLOYEE_ADD_FAIL = 'EMPLOYEE_ADD_FAIL' 

module.exports = {
    EMPLOYEE_LIST_REQUEST,
    EMPLOYEE_LIST_SUCCESS,
    EMPLOYEE_LIST_FAIL,
    EMPLOYEE_DETAILS_REQUEST,
    EMPLOYEE_DETAILS_SUCCESS,
    EMPLOYEE_DETAILS_FAIL,
    EMPLOYEE_ADD_REQUEST,
    EMPLOYEE_ADD_SUCCESS,
    EMPLOYEE_ADD_FAIL
};